### ISSUE TITLE
Cannot build code with node 8

### ISSUE THREAD

**Issue by whitecat** [Parrit/Parrit#110]
```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.4 x86_64
Node:         8, 8.6, 8.12, 8.17,  12.14.1
```

Notes:
I tried the following process with all the node versions listed above none of them worked. I am not sure what I am doing incorrectly.

Steps to reproduce:

1. Clone parrit 
2. Type in terminal `docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=parrit -e POSTGRES_USER=parrit -e POSTGRES_DB=local_parrit postgres` This starts docker postgres instance
3. Type in terminal `nvm use 8.*` To use one of the versions of node above.
4. Type in terminal `./gradlew bootRun`

Expected behavior:
Parrit starts up at localhost

Actual behavior
```
> Task :jsBuild FAILED
/Users/bobthebuilder/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:66
                        .replace(
                        ^

SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape
    at pathToArgumentName (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:66:4)
    at addFlag (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:170:16)
    at traverse (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:243:21)
    at traverse (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:299:23)
    at traverse (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:248:24)
    at Object.getArguments (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack/lib/cli.js:308:2)
    at Object.<anonymous> (/Users/cthom409/dev/Parrit/frontend/node_modules/webpack-cli/lib/utils/cli-flags.js:174:26)
    at Module._compile (/Users/cthom409/dev/Parrit/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jsBuild'.
> Process 'command './node_modules/.bin/webpack'' finished with non-zero exit value 1

```

**Comment by whitecat** [comment]
The problem was fixed by updating node to the most recent version 14.17 The documentation in the wiki should be updated to say that Node 8 is not used any longer, and Node 14 is necessary for building the project.
